// src/presentation/window_manager.rs
use std::cell::RefCell;
use crate::HelloWindow;   // generated by slint::include_modules!()
use slint::ComponentHandle; // used for show
use crate::SimulatorWindow;
use crate::GraphWindow;

#[derive(Default)]
pub struct WindowManager {
    secondary: RefCell<Option<HelloWindow>>,
    simulator:        RefCell<Option<SimulatorWindow>>,
    simulator_timer:  RefCell<Option<slint::Timer>>,
    graph:        RefCell<Option<GraphWindow>>,
    graph_timer:  RefCell<Option<slint::Timer>>,
}
impl WindowManager {
    pub fn open_hello(&self) {
        let hello = HelloWindow::new().unwrap();
        hello.show().unwrap();
        *self.secondary.borrow_mut() = Some(hello);
    }
    pub fn open_simulator(&self, _plugin_path: String) -> SimulatorWindow {
        let simulator = SimulatorWindow::new().unwrap();
        self.initial_simulator_state(&simulator);
        simulator.show().unwrap();
        // The plugin at `_plugin_path` is loaded by the caller (app_controller)
        // via SimulatorService::load_plugin so errors can be surfaced on this window.
        simulator
    }
    
    /// Opens the graph window, reusing the existing one (and bringing it back
    /// to the front) if it's already open.
    pub fn open_graph(&self) -> GraphWindow {
        if let Some(existing) = self.graph.borrow().as_ref() {
            existing.show().unwrap();
            return existing.clone_strong();
        }
        let graph = GraphWindow::new().unwrap();
        graph.show().unwrap();
        *self.graph.borrow_mut() = Some(graph.clone_strong());
        graph
    }

    pub fn set_graph_timer(&self, timer: slint::Timer) {
        *self.graph_timer.borrow_mut() = Some(timer);
    }

    pub fn close_all(&self) {
        *self.secondary.borrow_mut() = None;
        *self.simulator.borrow_mut()       = None;
        *self.simulator_timer.borrow_mut() = None;
        *self.graph.borrow_mut()       = None;
        *self.graph_timer.borrow_mut() = None;
    }

    pub fn set_simulator_timer(&self, timer: slint::Timer) {
        *self.simulator_timer.borrow_mut() = Some(timer);
    }

    // private methods
    fn initial_simulator_state(&self, simulator: &SimulatorWindow) {
        simulator.set_has_audio(false);
        simulator.set_is_playing(false);
        simulator.set_is_bypassed(false);
        simulator.set_current_time(0.0);
        simulator.set_duration(0.0);
    }

}