// src/presentation/window_manager.rs
use std::cell::RefCell;
use crate::HelloWindow;   // generated by slint::include_modules!()
use slint::ComponentHandle; // used for show
#[derive(Default)]
pub struct WindowManager {
    secondary: RefCell<Option<HelloWindow>>,
}
impl WindowManager {
    pub fn open_hello(&self) {
        let hello = HelloWindow::new().unwrap();
        hello.show().unwrap();
        *self.secondary.borrow_mut() = Some(hello);
    }
    pub fn close_all(&self) {
        *self.secondary.borrow_mut() = None;
    }
}