// src/presentation/window_manager.rs
use std::cell::RefCell;
use crate::HelloWindow;   // generated by slint::include_modules!()
use slint::ComponentHandle; // used for show
use crate::SimulatorWindow;

#[derive(Default)]
pub struct WindowManager {
    secondary: RefCell<Option<HelloWindow>>,
    simulator: RefCell<Option<SimulatorWindow>>,
}
impl WindowManager {
    pub fn open_hello(&self) {
        let hello = HelloWindow::new().unwrap();
        hello.show().unwrap();
        *self.secondary.borrow_mut() = Some(hello);
    }
    pub fn open_simulator(&self) {
        let simulator = SimulatorWindow::new().unwrap();
        self.initial_simulator_state(&simulator);
        simulator.show().unwrap();
        *self.simulator.borrow_mut() = Some(simulator);
    }
    
    // Future implementation for the graph window
    pub fn open_graph_window(&self) {
        println!("Graph window opened.");
    }

    pub fn close_all(&self) {
        *self.secondary.borrow_mut() = None;
        *self.simulator.borrow_mut() = None;
    }

    // private methods
    fn initial_simulator_state(&self, simulator: &SimulatorWindow) {
        simulator.set_has_audio(false);
        simulator.set_is_playing(false);
        simulator.set_is_bypassed(false);
        simulator.set_current_time(0.0);
        simulator.set_duration(0.0);
    }

}