[package]
name = "HeadroomLab"
version = "0.1.0"
edition = "2024"

[dependencies]
rfd = "0.17.2"
cpal     = "0.15"
symphonia = { version = "0.5", features = ["wav", "mp3", "vorbis", "aac"] }
libloading = "0.8"
rustfft = "6"
eframe = "0.35.0"
egui_plot = "0.36.0"

[profile.release]
codegen-units = 1
lto = true
